export type NationalApartmentItem = {
  name: string;
  address: string;
  addressType: "road" | "jibun";
};

export const nationalApartmentCatalog: NationalApartmentItem[] = [
  { name: "래미안 대치팰리스", address: "서울특별시 강남구 삼성로 151", addressType: "road" },
  { name: "헬리오시티", address: "서울특별시 송파구 송파대로 345", addressType: "road" },
  { name: "아크로리버파크", address: "서울특별시 서초구 신반포로 270", addressType: "road" },
  { name: "마포래미안푸르지오", address: "서울특별시 마포구 마포대로 195", addressType: "road" },
  { name: "고덕그라시움", address: "서울특별시 강동구 고덕로 333", addressType: "road" },
  { name: "잠실엘스", address: "서울특별시 송파구 올림픽로 99", addressType: "road" },
  { name: "e편한세상 용인한숲시티", address: "경기도 용인시 처인구 남사읍 한숲로 45", addressType: "road" },
  { name: "광교중흥S클래스", address: "경기도 수원시 영통구 광교호수공원로 20", addressType: "road" },
  { name: "동탄역 롯데캐슬", address: "경기도 화성시 동탄대로 537", addressType: "road" },
  { name: "평촌더샵아이파크", address: "경기도 안양시 동안구 관평로 101", addressType: "road" },
  { name: "분당파크뷰", address: "경기도 성남시 분당구 정자로 13", addressType: "road" },
  { name: "센텀파크", address: "부산광역시 해운대구 센텀중앙로 145", addressType: "road" },
  { name: "마린시티자이", address: "부산광역시 해운대구 마린시티3로 52", addressType: "road" },
  { name: "화명롯데캐슬카이저", address: "부산광역시 북구 금곡대로 166", addressType: "road" },
  { name: "대연 롯데캐슬레전드", address: "부산광역시 남구 수영로 345", addressType: "road" },
  { name: "만덕센트럴푸르지오", address: "부산광역시 북구 만덕대로 155", addressType: "road" },
  { name: "힐스테이트범어", address: "대구광역시 수성구 동대구로 386", addressType: "road" },
  { name: "범어두산위브더제니스", address: "대구광역시 수성구 달구벌대로 2435", addressType: "road" },
  { name: "월배아이파크", address: "대구광역시 달서구 조암남로 132", addressType: "road" },
  { name: "침산코오롱하늘채", address: "대구광역시 북구 침산남로 122", addressType: "road" },
  { name: "검단신도시우미린더시그니처", address: "인천광역시 서구 이음대로 378", addressType: "road" },
  { name: "송도더샵센트럴시티", address: "인천광역시 연수구 인천타워대로 323", addressType: "road" },
  { name: "청라힐데스하임", address: "인천광역시 서구 청라커낼로 292", addressType: "road" },
  { name: "부평아이파크", address: "인천광역시 부평구 부평대로 180", addressType: "road" },
  { name: "광주계림아이파크SK뷰", address: "광주광역시 동구 필문대로 115", addressType: "road" },
  { name: "수완대주피오레", address: "광주광역시 광산구 수완로 72", addressType: "road" },
  { name: "봉선한국아델리움", address: "광주광역시 남구 봉선로 120", addressType: "road" },
  { name: "상무자이", address: "광주광역시 서구 상무중앙로 110", addressType: "road" },
  { name: "문흥라인아파트", address: "광주광역시 북구 문흥로 35", addressType: "road" },
  { name: "둔산크로바", address: "대전광역시 서구 둔산로 155", addressType: "road" },
  { name: "도안아이파크시티", address: "대전광역시 유성구 도안대로 560", addressType: "road" },
  { name: "노은해랑숲마을", address: "대전광역시 유성구 은구비남로 17", addressType: "road" },
  { name: "관저더샵2차", address: "대전광역시 서구 관저중로 62", addressType: "road" },
  { name: "문수로아이파크", address: "울산광역시 남구 봉월로 116", addressType: "road" },
  { name: "약사더샵", address: "울산광역시 중구 번영로 571", addressType: "road" },
  { name: "옥동KCC스위첸", address: "울산광역시 남구 문수로 377", addressType: "road" },
  { name: "새뜸마을14단지", address: "세종특별자치시 다정북로 109", addressType: "road" },
  { name: "첫마을6단지", address: "세종특별자치시 도움1로 105", addressType: "road" },
  { name: "해밀마을1단지", address: "세종특별자치시 해밀3로 32", addressType: "road" },
  { name: "춘천롯데캐슬위너클래스", address: "강원특별자치도 춘천시 춘천로 363", addressType: "road" },
  { name: "원주기업도시이지더원", address: "강원특별자치도 원주시 지정면 신지정로 322", addressType: "road" },
  { name: "강릉유천지구푸르지오", address: "강원특별자치도 강릉시 선수촌로 77", addressType: "road" },
  { name: "청주가경아이파크", address: "충청북도 청주시 흥덕구 서현중로 66", addressType: "road" },
  { name: "충주호암힐데스하임", address: "충청북도 충주시 호암수청2로 21", addressType: "road" },
  { name: "제천강저푸르지오", address: "충청북도 제천시 강저로 42", addressType: "road" },
  { name: "천안불당지웰시티", address: "충청남도 천안시 서북구 불당25로 146", addressType: "road" },
  { name: "아산배방한성필하우스", address: "충청남도 아산시 배방읍 북수로 183", addressType: "road" },
  { name: "내포신도시모아엘가", address: "충청남도 홍성군 홍북읍 청사로 150", addressType: "road" },
  { name: "전주효자더샵", address: "전북특별자치도 전주시 완산구 세내로 287", addressType: "road" },
  { name: "군산디오션시티더샵", address: "전북특별자치도 군산시 궁포3로 24", addressType: "road" },
  { name: "익산부송아이파크", address: "전북특별자치도 익산시 무왕로 1425", addressType: "road" },
  { name: "순천신대중흥S클래스", address: "전라남도 순천시 해룡면 향매로 67", addressType: "road" },
  { name: "여수웅천포레나", address: "전라남도 여수시 예울마루로 35", addressType: "road" },
  { name: "목포옥암푸르지오", address: "전라남도 목포시 부흥로 85", addressType: "road" },
  { name: "포항자이", address: "경상북도 포항시 남구 대이로 85", addressType: "road" },
  { name: "구미문성태왕아너스", address: "경상북도 구미시 고아읍 들성로 199", addressType: "road" },
  { name: "경산중산자이", address: "경상북도 경산시 펜타힐즈2로 57", addressType: "road" },
  { name: "창원유니시티", address: "경상남도 창원시 의창구 중동중앙로 47", addressType: "road" },
  { name: "진주혁신도시중흥S클래스", address: "경상남도 진주시 충의로 20", addressType: "road" },
  { name: "김해율하이편한세상", address: "경상남도 김해시 율하2로 112", addressType: "road" },
  { name: "양산물금더샵", address: "경상남도 양산시 물금읍 증산역로 177", addressType: "road" },
  { name: "제주노형아이파크", address: "제주특별자치도 제주시 1100로 3349", addressType: "road" },
  { name: "서귀포혁신도시중흥S클래스", address: "제주특별자치도 서귀포시 신서로 51", addressType: "road" },
  { name: "제주삼화부영", address: "제주특별자치도 제주시 화삼로 72", addressType: "road" }
];
